idp:
  port: 3000
  host: "localhost"

auth:
  sign_key: "Th1s!sMyR4Nd0MStri4gPleaseChangeIt"

hydra:
  admin: "http://localhost:4445"
  api: "http://localhost:4444"
  client_id: "idp"
  client_secret: "idp-secret"
  remember_for: 360000

db:
  host: "localhost"
  port: "54320"
  name: "idp_dev"
  user: "idp"
  sslmode: false
  password: "8GWbz2JF4FMe1Q8X"

mail:
  active: "true"
  smtp: "smtp.gmail.com"
  port: "465"
  user: "hiveonid"
  password: "hiveon!23"
  from: "HiveonId@support.com"

redis:
  host: "127.0.0.1"
  port: 6379
  db: 1
  password: ""

security:
  use_casbin: false


  